name: Run Module Tests

on:
  [push]

jobs:
  test-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx pytest-html python-dotenv aiofiles jsonschema pytest-asyncio
    - name: Run Module D Tests
      run: pytest -s api_integration_testing/module_d/tests/ --html=report_module_d.html
    - name: Run Module C Tests
      run: pytest -s api_integration_testing/module_c/tests/ --html=report_module_c.html
    - name: Upload HTML reports
      uses: actions/upload-artifact@v2
      with:
        name: HTML-reports
        path: |
          report_module_d.html
          report_module_c.html