name: Run Module Tests

on:
  workflow_dispatch # Allow manual triggering of the workflow
  #[push] # Trigger the workflow on push events

jobs:
  test-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [module_d, module_c]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx pytest-html python-dotenv aiofiles jsonschema pytest-asyncio
    - name: Run Tests
      run: pytest -s api_integration_testing/${{ matrix.module }}/tests/ --html=report_${{ matrix.module }}.html
    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: HTML-report-${{ matrix.module }}
        path: report_${{ matrix.module }}.html